import React from 'react';
import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({

  "en":{   
    p1: "Login",
    p2: "Promotion",
    p3: "Coupon",
    p4: "Home",
    p5: "Point",
    p6: "Brand",
    p7: "Optometrist",
    p8: "Others",
    p9: "Welcome",
    p10: "Sorry, please login before using coupon",
    p11: "Email or phone number",
    p12: "Password",
    p13: "Forget Password",
    p14: "Register",
    p15: "Or",
    p16: "Login with Facebook",
    p17: "Daily login",
    p18: "Please share your coupon code or confirm QR code",
    p19: "Confirm using coupon",
    p20: "Scan the QR code at the staff screen to confirm use of the coupon",
    p21: "Coupon is used",
    p22: "Confirm",
    p23: "Your Reward Points",
    p24: "Reward Point Conditions",
    p25: "Using Points History",
    p26: "Use Points", 
    p27: "Collected Coins",
    p28: "Your Collected Coins",
    p29: "Using Coins History",
    p30: "Receiving Reward Points",
    p31: "Reward Coin Conditions",
    p32: "Product Brands",
    p33: "Eyewear",
    p34: "Optical Lens",
    p35: "Photos",
    p36: "Member ",
    p37: "Level",
    p38: "First Name",
    p39: "Last Name",
    p40: "Birthday",
    p41: "Email or phone number",
    p42: "Phone",
    p43: "Gender",
    p44: "Male",
    p45: "Female",
    p46: "Change Password",
    p47: "Save Changes",
    p48: "Old Password",
    p49: "New Password",
    p50: "Confirm New Password",
    p51: "New password will be sent to your phone number or registered email",
    p52: "Requires New Password",
    p53: "New password has been sent",
    p54: "Please enter an email address",
    p55: "Enter the password again",
    p56: "Confirm Registration",
    p57: "Register with Facebook",
    p58: "OTP code has been sent",
    p59: "OTP code",
    p60: "Requires new OTP code",
    p61: "Completed Registeration",
    p62: "You can login with the registered phone number and password",
    p63: "Member Registration Completed",
    p64: "Please confirm the registered email ",
    p65: "New password changed, you can now use the new password to login",
    p66: "Photo Album",
    p67: "Album",
    p68: "Appointment",
    p69: "Choose type of appointment",
    p70: "Choose an eye doctor to make an appointment with",
    p71: "Select a doctor",
    p72: "Required Appointed Date",
    p73: "Appointed Time",
    p74: "Explanation of Eye Issues",
    p75: "Please Specify",
    p76: "Appointer",
    p77: "Contact Number",
    p78: "Confirm an appointment",
    p79: "Appointment",
    p80: "Article",
    p81: "Article pictures",
    p82: "Contact us",
    p83: "Channels to follow us",
    p84: "Please, login to enable this function",
    p85: "Change language",
    p86: "Log out",
    p87: "Completed Appointment",
    p89: "Home",
    p90: "choose time",
    p91: "Success",
    p92: "Call",
    p93: "Google Map",
    p94: "email",
    p95: "select date",
    p96: "for staff to use",
    p97: "Completed Register",
    p98: "Please confirm",
    p99: "the registered email",
    p100: "Confirm OTP",
    p101: "to the registered phone number",
    p102: "Coins",
    p103: "Points",
    p104: "Phone",
    p105: "Exit Chavalit Application?",
    p106: "Cancel",
    p107: "Ok",
    p108: "coin",
    p109: "point",
    p110: "close",
    p111: "Not History",
    p112: "Not! picture in the gallery",
    p113: "Get points for buying products.",
    p114: "Use points."

},
"th":{
    p1: "เข้าสู่ระบบ",
    p2: "โปรโมชั่น",
    p3: "คูปอง",
    p4: "หน้าหลัก",
    p5: "คะแนน",
    p6: "แบรนด์",
    p7: "หมอสายตา",
    p8: "อื่นๆ",
    p9: "ยินดีต้อนรับ",
    p10: "ขออภัย กรุณาเข้าสู่ระบบก่อนใช้คูปอง",
    p11: "อีเมลหรือเบอร์โทรศัพท์",
    p12: "รหัสผ่าน",
    p13: "ลืมรหัสผ่าน",
    p14: "สมัครสมาชิก",
    p15: "หรือ",
    p16: "เข้าสู่ระบบผ่าน facebook",
    p17: "เข้าสู่ระบบประจำวัน",
    p18: "กรุณาแจ้งรหัสคูปอง หรือยืนยัน QR Code",
    p19: "ยืนยันการใช้คูปอง",
    p20: "สแกน QR Code ที่หน้าจอของเจ้าหน้าที่ เพื่อยืนยันการใช้คูปองของท่าน",
    p21: "ใช้คูปองเรียบร้อยแล้ว",
    p22: "ยืนยัน",
    p23: "คุณมีคะแนนสะสม",
    p24: "เงื่อนไขการได้คะแนน",
    p25: "ประวัติการใช้คะแนน",
    p26: "ใช้คะแนน",
    p27: "เหรียญสะสม",
    p28: "คุณมีเหรียญสะสม",
    p29: "ประวัติการใช้เหรียญ",
    p30: "ได้รับคะแนนสะสม",
    p31: "เงื่อนไขการได้เหรียญ",
    p32: "แบรนด์สินค้า",
    p33: "กรอบแว่น",
    p34: "เลนส์แว่นตา",
    p35: "ดูภาพประกอบอื่นๆ",
    p36: "ข้อมูลสมาชิก",
    p37: "ระดับสมาชิก",
    p38: "ชื่อ",
    p39: "นามสกุล",
    p40: "วันเกิด",
    p41: "อีเมลหรือเบอร์โทรศัพท์",
    p42: "เบอร์ติดต่อ",
    p43: "เพศ",
    p44: "ชาย",
    p45: "หญิง",
    p46: "เปลี่ยนรหัสผ่าน",
    p47: "ยืนยันการเปลี่ยนแปลง",
    p48: "รหัสผ่านเดิม",
    p49: "รหัสผ่านใหม่",
    p50: "ยืนยันรหัสผ่านใหม่",
    p51: "ระบบจะสร้างรหัสผ่านใหม่และส่งให้ท่านทางเบอร์โทรศัพท์หรืออีเมลที่ท่านได้ลงทะเบียนไว้",
    p52: "ขอรหัสผ่านใหม่",
    p53: "ส่งรหัสผ่านใหม่ให้ท่านเรียบร้อยแล้ว",
    p54: "กรุณากรอกอีเมล",
    p55: "กรอกรหัสผ่านอีกครั้ง",
    p56: "ยืนยันการสมัคร",
    p57: "สมัครโดยใช้ facebook",
    p58: "ระบบได้ทำการส่งรหัส otp สำหรับการยืนยันการสมัครไปยังเบอร์โทรศัพ์ที่ท่านลงทะเบียนไว้",
    p59: "รหัส otp",
    p60: "ขอรหัส otp ใหม่",
    p61: "สมัครเสร็จสิ้น",
    p62: "ท่านสามารถเข้าสู่ระบบ โดยใช้เบอร์โทรศัพท์และรหัสผ่านที่ท่านได้ลงทะเบียนไว้",
    p63: "สมัครสมาชิกเสร็จสิ้น",
    p64: "กรุณายืนยันการสมัครผ่านอีเมลที่ท่านได้ลงทะเบียนไว้",
    p65: "เปลี่ยนรหัสผ่านใหม่เรียบร้อยแล้ว ท่านสามารถใช้รหัสผ่านใหม่เพื่อเข้าสู่ระบบได้ทันที",
    p66: "อัลบั้มรวมภาพ",
    p67: "อัลบั้มภาพ",
    p68: "นัดหมายการเข้าตรวจ",
    p69: "เลือกการนัดหมาย",
    p70: "เลือกหมอสายตาที่ต้องการนัดหมาย",
    p71: "เลือกรายชื่อ",
    p72: "วันที่ต้องการนัดหมาย",
    p73: "เวลานัดหมาย",
    p74: "คำอธิบายปัญหาสายตาเบื้องต้น",
    p75: "โปรดระบุ",
    p76: "ผู้ทำการนัดหมาย",
    p77: "เบอร์ติดต่อกลับ",
    p78: "ยืนยันการนัดหมาย",
    p79: "นัดหมาย",
    p80: "บทความ",
    p81: "ภาพประกอบบทความ",
    p82: "ติดต่อเรา",
    p83: "ช่องทางติดตามเรา",
    p84: "กรุณาเข้าสู่ระบบ เพื่อเปิดใช้งานส่วนนี้",
    p85: "เปลี่ยนภาษา",
    p86: "ออกจากระบบ",
    p87: "การนัดหมายเสร็จสิ้น",
    p89: "กลับสู่หน้าแรก",
    p90: "เลือกเวลา",
    p91: "สำเร็จ",
    p92: "โทร",
    p93: "เปิด Google Map",
    p94: "อีเมล",
    p95: "เลือกวันเกิด",
    p96: "แก่เจ้าหน้าที่หากต้องการใช้สิทธิ",
    p97: "การสมัครเสร็จสิ้น",
    p98: "กรุณายืนยันการสมัคร",
    p99: "ผ่านอีเมลที่ท่านได้ลงทะเบียนไว้",
    p100: "ยืนยัน OTP",
    p101: "ไปยังเบอร์โทรศัพ์ที่ท่านลงทะเบียนไว้",
    p102: "เหรียญสะสม",
    p103: "คะแนนสะสม",
    p104: "เบอร์โทรศัพท์",
    p105: "ต้องการออกจากระบบ?",
    p106: "ยกเลิก",
    p107: "ตกลง",
    p108: "เหรียญ",
    p109: "คะแนน",
    p110:"ปิดหน้าต่าง",
    p111: "ไม่มีประวัติการใช้งาน",
    p112: "ไม่มีรูปภาพในอัลบั้มบทความนี้",
    p113: "ได้รับคะแนนจากการซื้อสินค้า",
    p114: "ใช้คะแนน"
  
 }
});
export default strings;